In [1]:
import os
os.chdir('/Users/layne/Desktop/aiqc')
os.getcwd()

'/Users/layne/Desktop/aiqc'

In [2]:
import aiqc
from aiqc import datum

/Users/layne/.pyenv/versions/3.7.6/envs/jupyterlab/lib/python3.7/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [3]:
datum.list_datums(format='df')

,name,dataset_type,analysis_type,label,label_classes,features,samples,description,location
0,exoplanets.parquet,tabular,regression,SurfaceTempK,N/A,8,433,Predict temperature of exoplanet.,local
1,heart_failure.parquet,tabular,regression,died,2,12,299,Biometrics to predict loss of life.,local
2,iris.tsv,tabular,classification_multi,species,3,4,150,"3 species of flowers. Only 150 rows, so cross-folds not represent population.",local
3,sonar.csv,tabular,classification_binary,object,2,60,208,"Detecting either a rock ""R"" or mine ""M"". Each feature is a sensor reading.",local
4,houses.csv,tabular,regression,price,N/A,12,506,Predict the price of the house.,local
5,iris_noHeaders.csv,tabular,classification multi,species,3,4,150,For testing; no column names.,local
6,iris_10x.tsv,tabular,classification multi,species,3,4,1500,For testing; duplicated 10x so cross-folds represent population.,local
7,brain_tumor,image,classification_binary,status,2,N/A images,80,Detect tumor in brain. No guarantee on healthy.,remote

In [4]:
names = datum.list_datums(format='df')['name']

In [5]:
for n in names:
    print(datum.get_datum_path(file_name=n))

/Users/layne/Desktop/aiqc/aiqc/data/exoplanets.parquet
/Users/layne/Desktop/aiqc/aiqc/data/heart_failure.parquet
/Users/layne/Desktop/aiqc/aiqc/data/iris.tsv
/Users/layne/Desktop/aiqc/aiqc/data/sonar.csv
/Users/layne/Desktop/aiqc/aiqc/data/houses.csv
/Users/layne/Desktop/aiqc/aiqc/data/iris_noHeaders.csv
/Users/layne/Desktop/aiqc/aiqc/data/iris_10x.tsv
https://github.com/aiqc/aiqc/remote_datum/image/brain_tumor/tabular_manifest.csv?raw=true

In [6]:
for n in names:
    print(datum.datum_to_pandas(file_name=n))

      TypeFlag  PlanetaryMassJpt   PeriodDays  SurfaceTempK  \
5            0            0.2500    19.224180         707.2
6            0            0.1700    39.031060         557.9
7            0            0.0220     1.592851        1601.5
15           0            1.2400     2.705782        2190.0
16           0            0.0195     1.580404         604.0
...        ...               ...          ...           ...
3557         0            0.2200     6.212290         783.1
3574         0            4.0630     4.124461        1161.5
3577         0            3.3280     5.452700        1335.3
3581         0            1.3600   395.400000         256.8
3582         0            1.0180  1605.800000         160.2

      DistFromSunParsec  HostStarMassSlrMass  HostStarRadiusSlrRad  \
5                650.00                1.070                1.0200
6                650.00                1.070                1.0200
7                650.00                1.070                1.0200
15               200.00                1.630                2.1800
16                14.55                0.176                0.2213
...                 ...                  ...                   ...
3557             380.00                0.880                0.7700
3574             254.00                0.947                1.1050
3577             257.00                1.392                1.5350
3581              68.50                1.000                1.2200
3582              68.50                1.000                1.2200

      HostStarMetallicity  HostStarTempK
5                    0.12         5777.0
6                    0.12         5777.0
7                    0.12         5777.0
15                   0.12         6490.0
16                   0.10         3250.0
...                   ...            ...
3557                 0.30         5080.0
3574                 0.01         5588.0
3577                 0.22         6442.0
3581                 0.14         5407.0
3582                 0.14         5407.0

[433 rows x 9 columns]
      age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0    75.0        0                     582.0         0               20.0
1    55.0        0                    7861.0         0               38.0
2    65.0        0                     146.0         0               20.0
3    50.0        1                     111.0         0               20.0
4    65.0        1                     160.0         1               20.0
..    ...      ...                       ...       ...                ...
294  62.0        0                      61.0         1               38.0
295  55.0        0                    1820.0         0               38.0
296  45.0        0                    2060.0         1               60.0
297  45.0        0                    2413.0         0               38.0
298  50.0        0                     196.0         0               45.0

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                      1  265000.00               1.9         130.0    1
1                      0  263358.03               1.1         136.0    1
2                      0  162000.00               1.3         129.0    1
3                      0  210000.00               1.9         137.0    1
4                      0  327000.00               2.7         116.0    0
..                   ...        ...               ...           ...  ...
294                    1  155000.00               1.1         143.0    1
295                    0  270000.00               1.2         139.0    0
296                    0  742000.00               0.8         138.0    0
297                    0  140000.00               1.4         140.0    1
298                    0  395000.00               1.6         136.0    1

     smoking  time_since  died
0          0         4.0     1
1          0         6.0     1
2          1         7.0     1
3          0         7.0     1
4          0         8.0     1
..       ...         ...   ...
294        1       270.0     0
295        0       271.0     0
296        0       278.0     0
297        1       280.0     0
298        1       285.0     0

[299 rows x 13 columns]
     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]
          a       b       c       d       e       f       g       h       i  \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843

          j       k       l       m       n       o       p       q       r  \
0    0.2111  0.1609  0.1582  0.2238  0.0645  0.0660  0.2273  0.3100  0.2999
1    0.2872  0.4918  0.6552  0.6919  0.7797  0.7464  0.9444  1.0000  0.8874
2    0.6194  0.6333  0.7060  0.5544  0.5320  0.6479  0.6931  0.6759  0.7551
3    0.1264  0.0881  0.1992  0.0184  0.2261  0.1729  0.2131  0.0693  0.2281
4    0.4459  0.4152  0.3952  0.4256  0.4135  0.4528  0.5326  0.7306  0.6193
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
203  0.2684  0.3108  0.2933  0.2275  0.0994  0.1801  0.2200  0.2732  0.2862
204  0.2154  0.3085  0.3425  0.2990  0.1402  0.1235  0.1534  0.1901  0.2429
205  0.2529  0.2716  0.2374  0.1878  0.0983  0.0683  0.1503  0.1723  0.2339
206  0.2354  0.2898  0.2812  0.1578  0.0273  0.0673  0.1444  0.2070  0.2645
207  0.2354  0.2720  0.2442  0.1665  0.0336  0.1302  0.1708  0.2177  0.3175

          s       t       u       v       w       x       y       z      aa  \
0    0.5078  0.4797  0.5783  0.5071  0.4328  0.5550  0.6711  0.6415  0.7104
1    0.8024  0.7818  0.5212  0.4052  0.3957  0.3914  0.3250  0.3200  0.3271
2    0.8929  0.8619  0.7974  0.6737  0.4293  0.3648  0.5331  0.2413  0.5070
3    0.4060  0.3973  0.2741  0.3690  0.5556  0.4846  0.3140  0.5334  0.5256
4    0.2032  0.4636  0.4148  0.4292  0.5730  0.5399  0.3161  0.2285  0.6995
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
203  0.2034  0.1740  0.4130  0.6879  0.8120  0.8453  0.8919  0.9300  0.9987
204  0.2120  0.2395  0.3272  0.5949  0.8302  0.9045  0.9888  0.9912  0.9448
205  0.1962  0.1395  0.3164  0.5888  0.7631  0.8473  0.9424  0.9986  0.9699
206  0.2828  0.4293  0.5685  0.6990  0.7246  0.7622  0.9242  1.0000  0.9979
207  0.3714  0.4552  0.5700  0.7397  0.8062  0.8837  0.9432  1.0000  0.9375

         ab      ac      ad      ae      af      ag      ah      ai      aj  \
0    0.8080  0.6791  0.3857  0.1307  0.2604  0.5121  0.7547  0.8537  0.8507
1    0.2767  0.4423  0.2028  0.3788  0.2947  0.1984  0.2341  0.1306  0.4182
2    0.8533  0.6036  0.8514  0.8512  0.5045  0.1862  0.2709  0.4232  0.3043
3    0.2520  0.2090  0.3559  0.6260  0.7340  0.6120  0.3497  0.3953  0.3012
4    1.0000  0.7262  0.4724  0.5103  0.5459  0.2881  0.0981  0.1951  0.4181
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
203  1.0000  0.8104  0.6199  0.6041  0.5547  0.4160  0.1472  0.0849  0.0608
204  1.0000  0.9092  0.7412  0.7691  0.7117  0.5304  0.2131  0.0928  0.1297
205  1.0000  0.8630  0.6979  0.7717  0.7305  0.5197  0.1786  0.1098  0.1446
206  0.8297  0.7032  0.7141  0.6893  0.4961  0.2584  0.0969  0.0776  0.0364
207  0.7603  0.7123  0.8358  0.7622  0.4567  0.1715  0.1549  0.1641  0.1869

         ak      al      am      an      ao      ap      aq      ar      as  \
0    0.6692  0.6097  0.4943  0.2744  0.0510  0.2834  0.2825  0.4256  0.2641
1    0.3835  0.1057  0.1840  0.1970  0.1674  0.0583  0.1401  0.1628  0.0621
2    0.6116  0.6756  0.5375  0.4719  0.4647  0.2587  0.2129  0.2222  0.2111
3    0.5408  0.8814  0.9857  0.9167  0.6121  0.5006  0.3210  0.3202  0.4295
4    0.4604  0.3217  0.2828  0.2430  0.1979  0.2444  0.1847  0.0841  0.0692
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
203  0.0969  0.1411  0.1676  0.1200  0.1201  0.1036  0.1977  0.1339  0.0902
204  0.1159  0.1226  0.1768  0.0345  0.1562  0.0824  0.1149  0.1694  0.0954
205  0.1066  0.1440  0.1929  0.0325  0.1490  0.0328  0.0537  0.1309  0.0910
206  0.1572  0.1823  0.1349  0.0849  0.0492  0.1367  0.1552  0.1548  0.1319
207  0.2655  0.1713  0.0959  0.0768  0.0847  0.2076  0.2505  0.1862  0.1439

         at      au      av      aw      ax      ay      az      ba      bb  \
0    0.1386  0.1051  0.1343  0.0383  0.0324  0.0232  0.0027  0.0065  0.0159
1    0.0203  0.0530  0.0742  0.0409  0.0061  0.0125  0.0084  0.0089  0.0048
2    0.0176  0.1348  0.0744  0.0130  0.0106  0.0033  0.0232  0.0166  0.0095
3    0.3654  0.2655  0.1576  0.0681  0.0294  0.0241  0.0121  0.0036  0.0150
4    0.0528  0.0357  0.0085  0.0230  0.0046  0.0156  0.0031  0.0054  0.0105
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
203  0.1085  0.1521  0.1363  0.0858  0.0290  0.0203  0.0116  0.0098  0.0199
204  0.0080  0.0790  0.1255  0.0647  0.0179  0.0051  0.0061  0.0093  0.0135
205  0.0757  0.1059  0.1005  0.0535  0.0235  0.0155  0.0160  0.0029  0.0051
206  0.0985  0.1258  0.0954  0.0489  0.0241  0.0042  0.0086  0.0046  0.0126
207  0.1470  0.0991  0.0041  0.0154  0.0116  0.0181  0.0146  0.0129  0.0047

         bc      bd      be      bf      bg      bh object
0    0.0072  0.0167  0.0180  0.0084  0.0090  0.0032      R
1    0.0094  0.0191  0.0140  0.0049  0.0052  0.0044      R
2    0.0180  0.0244  0.0316  0.0164  0.0095  0.0078      R
3    0.0085  0.0073  0.0050  0.0044  0.0040  0.0117      R
4    0.0110  0.0015  0.0072  0.0048  0.0107  0.0094      R
..      ...     ...     ...     ...     ...     ...    ...
203  0.0033  0.0101  0.0065  0.0115  0.0193  0.0157      M
204  0.0063  0.0063  0.0034  0.0032  0.0062  0.0067      M
205  0.0062  0.0089  0.0140  0.0138  0.0077  0.0031      M
206  0.0036  0.0035  0.0034  0.0079  0.0036  0.0048      M
207  0.0039  0.0061  0.0040  0.0036  0.0061  0.0115      M

[208 rows x 61 columns]
        crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273

     ptratio  lstat  price
0       15.3   4.98   24.0
1       17.8   9.14   21.6
2       17.8   4.03   34.7
3       18.7   2.94   33.4
4       18.7   5.33   36.2
..       ...    ...    ...
501     21.0   9.67   22.4
502     21.0   9.08   20.6
503     21.0   5.64   23.9
504     21.0   6.48   22.0
505     21.0   7.88   11.9

[506 rows x 13 columns]
     5.1  3.5  1.4  0.2  0.0
0    4.9  3.0  1.4  0.2  0.0
1    4.7  3.2  1.3  0.2  0.0
2    4.6  3.1  1.5  0.2  0.0
3    5.0  3.6  1.4  0.2  0.0
4    5.4  3.9  1.7  0.4  0.0
..   ...  ...  ...  ...  ...
144  6.7  3.0  5.2  2.3  2.0
145  6.3  2.5  5.0  1.9  2.0
146  6.5  3.0  5.2  2.0  2.0
147  6.2  3.4  5.4  2.3  2.0
148  5.9  3.0  5.1  1.8  2.0

[149 rows x 5 columns]
      sepal_length  sepal_width  petal_length  petal_width  species
0              5.1          3.5           1.4          0.2        0
1              4.9          3.0           1.4          0.2        0
2              4.7          3.2           1.3          0.2        0
3              4.6          3.1           1.5          0.2        0
4              5.0          3.6           1.4          0.2        0
...            ...          ...           ...          ...      ...
1495           6.7          3.0           5.2          2.3        2
1496           6.3          2.5           5.0          1.9        2
1497           6.5          3.0           5.2          2.0        2
1498           6.2          3.4           5.4          2.3        2
1499           5.9          3.0           5.1          1.8        2

[1500 rows x 5 columns]

UnboundLocalError: local variable 'df' referenced before assignment

In [8]:
datum.datum_to_pandas(file_name='iris.tsv').dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species           int64
dtype: object